# Generated by Django 3.1.6 on 2021-02-08 09:03

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('article', '0004_articlecolumn_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlecolumn',
            name='tags',
        ),
        migrations.AddField(
            model_name='articlepost',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
